#!/bin/sh

PHP="{{ php_executable }}"
WWW_DIR="{{ target_directory }}/.."
MAINTENANCE_DIR="$WWW_DIR/w/maintenance"

EXIT_CODE=0

run_task() {
    set -x
    "$PHP" "$MAINTENANCE_DIR/run.php" "$@"
    set +x
    if [ "$?" -ne 0 ]
    then
        EXIT_CODE="$?"
    fi
}

run_task "runJobs.php"
run_task "namespaceDupes.php"
run_task "initSiteStats.php" --update
run_task "updateArticleCount.php" --update
run_task "generateSitemap.php" --fspath="$WWW_DIR/sitemap/" --identifier="{{ website_id }}" --urlpath=sitemap

exit "$EXIT_CODE"
